### ISSUE TITLE
您好，我想问一下token_vec_300.bin这个文件是什么？

### ISSUE THREAD

**Issue by lili1234567890** [liweimin1996/Min_NLP_Practice#1]
Traceback (most recent call last):
  File "bilstm_crf_train.py", line 178, in <module>
    ner = LSTMNER()
  File "bilstm_crf_train.py", line 62, in __init__
    self.embedding_matrix = self.build_embedding_matrix()
  File "bilstm_crf_train.py", line 119, in build_embedding_matrix
    embedding_dict = self.load_pretrained_embedding()
  File "bilstm_crf_train.py", line 106, in load_pretrained_embedding
    with open(self.embedding_file, 'r', encoding='UTF-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/zgy/wll/CwsPosNerCNNRNNLSTM-master/cws/model/token_vec_300.bin'

**Comment by hlstudio** [comment]
就中文字向量文件，一般是训练好的，直接以文件名为关键字可以搜索得到，例如：
https://github.com/liuhuanyong/ChineseEmbedding/raw/master/model/token_vec_300.bin

**Comment by lili1234567890** [comment]
学习您

**Comment by liweimin1996** [comment]
是预训练好的词向量，我有时间把它也发上去吧
